### ISSUE TITLE
How to define contracts functions in dart

### ISSUE THREAD

**Issue by Jeevananthan-23** [luv8860/GST-System#1]
Can u plz help me

**Comment by luv8860** [comment]
https://www.youtube.com/watch?v=3Eeh3pJ6PeA Refer this video for full explanation

**Comment by Jeevananthan-23** [comment]
i seen that one but im not clear abt that how to contact you in-person plz

**Comment by Jeevananthan-23** [comment]
[https://drive.google.com/drive/folders/1DBsmYnf3vXmb5cDC1HuAHwvZlpNmegL0?usp=sharing](url)
